remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Digital Garden of Joy the Gardener]
description: [Happy plants and happy minds.]
permalink: /:categories/:title/
